name: Build and Deploy Sphinx HTML

on:
  push:
    branches:
      - "master"

permissions:
  contents: write

jobs:
  deploy-html:
    runs-on: ubuntu-latest
    steps:
      #- name: Maximize build space
      #  uses: easimon/maximize-build-space@master
      #  with:
      #    root-reserve-mb: 512
      #    swap-size-mb: 1024
      #    remove-dotnet: 'true'
      #    remove-android: 'true'
      #    remove-haskell: 'true'
      #    remove-codeql: 'true'
    
      - uses: actions/checkout@v4

      - name: Build Sphinx HTML
        uses: ferdnyc/sphinx-action@468d403f5919b75235ac919d1f40ea830e601953
        with:
          docs-folder: "src/"
          pre-build-command: "pip install sphinx_rtd_theme"

      - name: Deploy HTML
        uses: peaceiris/actions-gh-pages@v3.9.1
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/html
          publish_branch: html
