name: Build and Deploy Sphinx PDF

on: 
  push:
    tags:
    - '*'

permissions:
  contents: write

jobs:
  deploy-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Sphinx PDF
        uses: ferdnyc/sphinx-action@468d403f5919b75235ac919d1f40ea830e601953
        with:
          docs-folder: "src/"
          pre-build-command: "pip install sphinx_rtd_theme && apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
          build-command: "make latexpdf"

      - name: Release PDF
        uses: ncipollo/release-action@v1.13.0
        with:
          artifactErrorsFailBuild: true
          artifacts: "f-4manual.pdf"
          artifactContentType: "application/pdf"
          generateReleaseNotes: true
          omitBody: true
          omitName: true
